boutiques/boutiques

- descriptor.schema.json
Created two new optional attributes for input and output:
* optional is a boolean (False if not present) that describes if the input/output is optional.
* command-line-flag is a string that defines the flag to prepend to the input/output value of any input. This is necessary to support optional inputs and outputs as their command-line flag shouldn't be put on the command-line if the input/output is not present. 
* optional outputs are output files that may or may not be produced by the tool
> #4 optional inputs and outputs; #2 Flag input type; #10 input file extensions.

- LICENSE
- tools/python/boutiques/schema/descriptor.schema.json
- tools/python/boutiques/schema/examples/bad.json
- tools/python/boutiques/schema/examples/good.json
- tools/python/boutiques/validator.py
- Updated validator to verify that command-line keys can be recycled over unique ids, so long as:
- neither is required,
- they are members of the same mutually exclusive group
- Updated examples to test successful and failed implementation of this feature
- Ensured we kept full test coverage of the validator after changes
- Updated licensing in a couple files
> updated validator for cl-key recycling

- tools/python/boutiques/schema/descriptor.schema.json
- tools/python/boutiques/schema/examples/bad.json
- tools/python/boutiques/schema/examples/good.json
Addresses #63, https://github.com/boutiques/boutiques-paper/issues/7.
Towards `0.5`, here are the known breaks in backwards compatibility now:
- `walltime-estimate` now resides in `suggested-resources`
- singularity hub container now treated like docker
> added resource requirements/suggestions to schema

- tools/python/boutiques/importer.py
- tools/python/boutiques/schema/examples/upgrade04.json
- tools/python/boutiques/tests/test_import.py
- tools/python/boutiques/validator.py
- tools/python/setup.py
- Adds importer for `0.4` versions of boutiques
- Verified structure of current singularity implementations for all known singularity descriptors deployed in CBRAIN with Natacha, and that this importer properly handles them 
- Added appropriate test
> Added importer for 0.4 and 0.4.5. descriptors to 0.5

- tools/python/boutiques/importer.py
- tools/python/boutiques/schema/examples/good.json
These broken indices are common, so this will remove the `http://` in front of them.
> updated importer to fix broken docker indices

- tools/python/boutiques/importer.py
- tools/python/setup.py
- would return an `indexError` unintentionally if no "`http://|https://`" were at the start of the Docker `container_index`, as it was trying to access the second (`[1]`) element in a 1-element list. Now, looks at the last element (`[-1]`) which can be either.
> bug fix in importer

- tools/python/boutiques/bosh.py
- tools/python/boutiques/tests/test_example1.py
- tools/python/boutiques/tests/test_exec.py
- tools/python/cleanup_tests.sh
Also added a script to clean-up test files (and revert changes to the `good.json`) after running tests.
Addresses #164
> removed -n option with random generation

- tools/python/boutiques/localExec.py
return exit_code in execute was tabbed within the final loop, so only checked the first file.
> Fixed a bug in localExec.py preventing all outputs from being checked

- tools/python/boutiques/schema/descriptor.schema.json
- tools/python/boutiques/schema/examples/example1/example1.json
- tools/python/boutiques/schema/examples/good.json
A tool descriptor may now contain a set of tags such as:
```
"tags": {
"domain": "testing",
"programming-language": "Python",
"foo": "bar"
}
```
It addresses #186. This is required for https://github.com/fli-iam/CARMIN/issues/79 
Besides, arrays `inputs`, `environment-variables`, `output-files` and `groups` cannot be empty and cannot contain duplicate elements.
> Tags and arrays

- tools/python/boutiques/schema/descriptor.schema.json
- tools/python/boutiques/schema/examples/good.json
Error codes can now be documented in a tool descriptor as follows:
```
"error-codes": [
{
"code": 1,
"description": "crashed"
},
{
"code": 12,
"description": "crashed badly"
}
]
```
This is useful in case a platform wants to report error messages to users.
Fixes #36.
Required by https://github.com/fli-iam/CARMIN/issues/61
> Added error codes to schema

- tools/python/boutiques/bosh.py
Fixing a small "invocation" typo in print
> Fixing "invocation" typo

- tools/python/boutiques/exporter.py
As described in the Swagger OpenAPI 3.0 descriptor, the pipeline id property should be named "identifier".
> Renaming CARMIN pipeline id property

- tools/python/boutiques/localExec.py
- tools/python/boutiques/tests/test_example1.py
- tools/python/boutiques/tests/test_example2.py
- tools/python/boutiques/tests/test_exec.py
- tools/python/setup.py
- updated `bosh` to return the exit code properly via the CLI
- now supports multiple indices for `container-image` in the context of `singularity`
- will properly download and rename images pulled through `singularity`, and won't download image if there is one in the working directory with the same name
This PR is necessary for `bosh` to work using Singularity on a cluster (tested on Compute Canada, Cedar). Post merging this, given another PR with small modifications, I will release `0.5.6-post1` on pypi.
> Modifications for Singularity

- tools/python/boutiques/bosh.py
- tools/python/boutiques/tests/test_example1.py
- tools/python/boutiques/tests/test_example2.py
- tools/python/boutiques/tests/test_exec.py
bosh simulate now returns a (fake) stdout, stderr, exit_code, err_msg tuple for consistency with execute.
> Fix for bug in simulate

- tools/python/boutiques/bosh.py
- tools/python/boutiques/publisher.py
- tools/python/boutiques/tests/test_publisher.py
- tools/python/requirements.txt
- tools/python/setup.py
Rewrote `bosh publish` to publish tools to Zenodo instead of Neurolinks, as discussed in #205 and #34.
Example of tool published: https://zenodo.org/record/1219701 Note the keywords, extracted from the descriptor tags, schema-version and container image type. Hopefully searching from keywords will be available in the coming Zenodo search API. Tool version (Zenodo's "version") is also extracted from the descriptor, as well as name (Zenodo's "title"). Creator and affiliation are passed on the CLI.
Option `--sandbox` publishes to https://sandbox.zenodo.org instead of https://zenodo.org
Auth token is asked interactively if not passed on the CLI or found in $HOME.boutiques. It is always stored in $HOME/.boutiques once available. In the test, authentication token is passed on the CLI. This is …
> Descriptor publication on Zenodo

- tools/python/boutiques/bosh.py
- tools/python/boutiques/invocationSchemaHandler.py
- tools/python/boutiques/localExec.py
- tools/python/boutiques/schema/examples/invalid_json.json
- tools/python/boutiques/schema/examples/no_container.json
- tools/python/boutiques/schema/examples/no_container_invocation.json
- tools/python/boutiques/tests/test_no_container.py
- tools/python/boutiques/tests/test_validator.py
- tools/python/boutiques/validator.py
* Added a test for tools with no container image (#172)
* `bosh` CLI now returns `99` in case an exception occurs, to reduce potential conflict with tool exit code.
* Added a test for invalid JSON descriptors and caught the exception in validator.
* Raised an exception when mandatory output file is not found (was just printing a message).
> Small fixes

- tools/python/boutiques/bosh.py
- tools/python/boutiques/tests/test_validator.py
- tools/python/boutiques/validator.py
Option '--format' of the validator now rewrites the descriptor with alphabetically ordered properties.
This follows the discussion in https://github.com/aces/cbrain-plugins-experimental/pull/23
> Validator can now reformat descriptors

- tools/python/boutiques/bosh.py
- tools/python/boutiques/creator.py
- tools/python/boutiques/tests/test_creator.py
- tools/python/setup.py
Creator can now inspect a Docker image to fill some properties. In particular:
* If there is an entrypoint, it will be added to the command line
* Tool version is set from the image tag
* Author and description are set from the corresponding properties of the image
It also sets the container-image properties correctly, including when Docker images have to be booted through Singularity (`--use-singularity` option).
> Docker image inspection in creator

- tools/python/boutiques/localExec.py
- tools/python/cleanup_tests.sh
(please excuse the incorrect branch name - I thought the errors were with validation at first!)
**Work in Progress**
Fixes addressed:
Previously, running the simulator on a descriptor with inputs would give a value like:
```
ndmg_pipeline  ''  ''  ''  ''  /ndmg_atlases/atlas/MNI152_T1_1mm.nii.gz  /ndmg_atlases/atlas/MNI152_T1_1mm_brain_mask.nii.gz  str_outdir_Fp  /ndmg_atlases/labels/DS01876.nii.gz  -c
```
Now we have the following, as expected:
```
ndmg_pipeline  f_dti_file_64.nii.gz  f_bval_file_35.cpp  f_bvec_file_88.mnc  f_mprage_file_63.csv  /ndmg_atlases/atlas/MNI152_T1_1mm.nii.gz  /ndmg_atlases/atlas/MNI152_T1_1mm_brain_mask.nii.gz  str_outdir_Om  /ndmg_atlases/labels/DS00833.nii.gz /ndmg_atlases/labels/DS00108.nii.gz /ndmg_atlases/labels/DS00833.nii.gz
```
Note, that values were …
> Bug fixes in simulator

- RELEASE.md
- schema/README.md
- tools/python/setup.py
* Bumped version number in `setup.py`
* Updated markdown version of schema
* Updated release instructions to add missing option for `jsonschema2md`
> Release 0.5.14

- tools/python/boutiques/bosh.py
- tools/python/boutiques/localExec.py
- tools/python/boutiques/publisher.py
- tools/python/boutiques/puller.py
- tools/python/boutiques/schema/examples/good.json
- tools/python/boutiques/searcher.py
- tools/python/boutiques/tests/test_example1.py
- tools/python/boutiques/tests/test_pull.py
- tools/python/boutiques/tests/test_search.py
- tools/python/setup.py
Issue #241 
`bosh search` searches Zenodo for all descriptors and returns a list like this:
`bosh search <search_query>` searches for a specific descriptor, for example `bosh search ndmg` will return:
`bosh pull <ZID>` downloads a descriptor from Zenodo using its ID prefixed with 'zenodo.' (as returned from bosh search), e.g. `bosh pull zenodo.1472823`
`bosh exec launch <ZID> <invocation>` launches an invocation using the pull functionality to open and use the descriptor directly from its published entry on Zenodo.
> Implemented bosh search and bosh pull, added ability to run directly from zenodo

- tools/python/boutiques/localExec.py
- tools/python/boutiques/schema/examples/no_spaces.json
There was a bug where list inputs appeared in the command line with an extra space at the end.
> Removed extra space at end of list inputs

- tools/python/boutiques/bosh.py
- tools/python/boutiques/publisher.py
- tools/python/boutiques/puller.py
- tools/python/boutiques/searcher.py
- tools/python/boutiques/tests/test_search.py
Issue #335
`bosh search` will return a maximum of 10 results by default, unless the `-m` option is used to specify a different number.
> Specify max number of results returned by bosh search

- tools/python/boutiques/bosh.py
- tools/python/boutiques/conftest.py
- tools/python/boutiques/exporter.py
- tools/python/boutiques/importer.py
- tools/python/boutiques/tests/test_evaluate.py
- tools/python/boutiques/tests/test_export.py
- tools/python/boutiques/tests/test_import.py
- tools/python/boutiques/tests/test_invocation.py
- tools/python/boutiques/tests/test_simulate.py
- tools/python/boutiques/tests/test_test.py
Issue #277 
Modified the following bosh functions to accept JSON objects and Zenodo IDs for descriptors and/or invocations:
* Test
* Export
* Import
Wrote test cases for accepting JSON objects/Zenodo IDs for all bosh functions. Some test cases were not written:
* Import: no Zenodo test because there are no published descriptors that use schema version 04 to test the `upgrade_04` function
* Export: no Zenodo test because the published "Example Boutiques Tool" has version 0.0.3 and the one used for the export tests has version 0.0.1. I could change it to 0.0.3 everywhere but I figured this would be tedious as we'd just need to change it again every time we publish a new version. 
* Publish: no test with JSON obj because published items must be files; no test with Zenodo since it doesn't …
> Add support for JSON objects/Zenodo IDs passed on the CLI in bosh

- tools/python/boutiques/puller.py
- tools/python/boutiques/searcher.py
Fixed a bug in `bosh pull` where if the descriptor isn't in the first 10 search results, it won't be found and the pull will fail. Instead of searching for all boutiques descriptors, it searches with the ZID as the query, which seems to always return the desired descriptor as the first and only result. 
Also added some info messages which I think are necessary even in non-verbose mode:
* `bosh search` prints the number of results displayed out of the total (so the user will know if there are additional results that were not displayed).
* `bosh pull` prints the name of the download folder (the cache directory) so the user will know where to find the pulled file.
> Minor changes to bosh search and pull

- tools/python/boutiques/bosh.py
- tools/python/boutiques/localExec.py
- tools/python/boutiques/schema/examples/good.json
- tools/python/boutiques/tests/test_prepare.py
- tools/python/setup.py
Issue #351 
Added `bosh exec prepare` which pulls the Docker or Singularity container image for a descriptor and prints the container location. In the case of a Singularity image, this method creates a lockfile for the image file so that multiple threads trying to pull the same image at the same time won't conflict with each other. Also added the option to specify a custom path for the Singularity image.
> Bosh exec prepare

- tools/python/boutiques/localExec.py
- tools/python/boutiques/tests/test_prepare.py
- tools/python/setup.py
`bosh prepare` creates a lock directory while pulling the Singularity image such that other processes trying to pull the same image will be blocked while they wait for the lockdir to no longer exist.
> Fixed bug + reimplemented bosh prepare to use a lockdir

- tools/python/boutiques/prettyprint.py
- tools/python/boutiques/schema/examples/test_pretty_print.json
Now tags print out like this:
```
Tags: domain: testing; foo: bar1, bar2; programming-language: Python
```
> fixed bug in tags

- tools/python/boutiques/bosh.py
- tools/python/boutiques/localExec.py
- tools/python/boutiques/publisher.py
- tools/python/boutiques/puller.py
- tools/python/boutiques/searcher.py
- tools/python/boutiques/tests/test_pull.py
- tools/python/boutiques/tests/test_search.py
1. Added "tests:y/n" keyword to Zenodo metadata on `bosh publish` (#328)
2. When doing a `bosh search`, any returned fields longer than 40 characters are truncated, unless the `--no-trunc` option is supplied (#356)
3. `bosh search` results are sorted in descending order by number of downloads (#360)
4. Puller checks if the cached file exists before pulling and returns it if it exists (#361)
> Zenodo Improvements

- tools/python/boutiques/__init__.py
- tools/python/boutiques/bosh.py
- tools/python/boutiques/tests/test_bosh.py
- tools/python/boutiques/tests/test_example1.py
- tools/python/boutiques/tests/test_example2.py
- tools/python/boutiques/tests/test_no_spaces.py
- tools/python/boutiques/tests/test_simulate.py
Added JSON printing in simulate, and a simplified wrapping for this:
```
$ # bosh example boutiques/schema/examples/example1/example1_docker.json
$ #   OR
$ bosh exec simulate boutiques/schema/examples/example1/example1_docker.json -j
{
"str_input_list": [
"str_str_input_list_NP",
"str_str_input_list_Xy",
"str_str_input_list_xW"
],
"str_input": "str_str_input_YT",
"list_int_input": [
"-27",
"8"
],
"config_num": 4,
"num_input": 0.9
}
```
> added simulation flag to print out jsons, added bosh example

- README.md
- tools/python/boutiques/bosh.py
- tools/python/boutiques/invocationSchemaHandler.py
- tools/python/boutiques/localExec.py
- tools/python/boutiques/schema/examples/example1/example1_docker.json
- tools/python/boutiques/schema/examples/example1/example1_docker_exported.json
- tools/python/boutiques/schema/examples/example1/example1_docker_exported_doi.json
- tools/python/boutiques/schema/examples/example1/example1_docker_exported_doi_python2.json
- tools/python/boutiques/schema/examples/example1/example1_docker_exported_python2.json
- tools/python/boutiques/schema/examples/example1/example1_docker_updated.json
- tools/python/boutiques/schema/examples/example1/example1_docker_with_doi.json
- tools/python/boutiques/schema/examples/example1/inv_no_defaults.json
- tools/python/boutiques/schema/examples/good.json
- tools/python/boutiques/tests/test_simulate.py
* (#362) Fixed bug where not providing a value for a mandatory input with a default value threw a schema validation error. The default values are temporarily added to the input dictionary right before the invocation is validated to prevent the error. 
* (#338) Default value is always used when a value is not provided, even when the input is optional.
* Minor fixes, including fixing indentation in `invocationSchemaHandler` and fixing the `example1` descriptors to have the proper default value for the `str_input_list` input.
> Default values are always used when input values are not provided, fixed validation error

- tools/python/boutiques/bosh.py
- tools/python/boutiques/localExec.py
- tools/python/boutiques/tests/test_prepare.py
Fixes for #404, #405 
* Fixed the `--imagepath` option in `bosh exec launch` and `bosh exec prepare` to be the absolute path of the Singularity image (this can refer to either an existing image file or the path you want the image to have when it's pulled)
* Made it so the lockdir is created in the same location as the imagepath, so that processes can be run from different locations using the same imagepath and it should not cause problems.
* Removed the `finally` clause that deletes the lockdir and pullfolder environment variable and replaced it with a method that does this only once a container image has been found locally or pulled successfully. The `finally` clause was causing a bug where if a process timed out while trying to pull the image, it would still delete the lockdir, causing …
> Fixed imagePath for bosh exec launch/prepare

- tools/python/boutiques/bosh.py
- tools/python/boutiques/searcher.py
- tools/python/requirements.txt
- I've in-lined the json String in test's call of bosh.py's invocation instead of exporting a temporary json file and passing that. Function is the same, but there is less code and intent is clearer. https://github.com/boutiques/boutiques/blob/97fe5b0e5824812202f7207e62b02af5c1e24216/tools/python/boutiques/bosh.py#L395-L404
- I've localised the loadJson call on result.invocation in invocation() to simplify the code as it is only used after the latter if statement and so you do not need the former. Function is the same, just cleaner. https://github.com/boutiques/boutiques/blob/97fe5b0e5824812202f7207e62b02af5c1e24216/tools/python/boutiques/bosh.py#L325-L340
- I have changed the read mode to "universal newline mode" as this was not the default in older python. These changes were only needed …
> Removed some redundant/ambigious code. Function is the same, but there is less code and intent is clearer

- tools/python/boutiques/bosh.py
- tools/python/boutiques/localExec.py
- tools/python/boutiques/publisher.py
- tools/python/boutiques/puller.py
- tools/python/boutiques/schema/examples/example1/example1_docker_with_doi.json
- tools/python/boutiques/searcher.py
- tools/python/boutiques/tests/boutiques_mocks.py
- tools/python/boutiques/tests/test_publisher.py
#393 
Added a `--replace <zenodo-id>` option to `bosh publish` to publish updated versions using the unique Zenodo ID.
> Explicit version consolidation

- tools/python/boutiques/localExec.py
- tools/python/boutiques/tests/test_simulate.py
Closes #442 
May also close #329 
These changes create a variable `number_decimals` separate from `nd` in `localExec`'s `_randomFillInDict` function, that explicitly represents the number of decimal places to round to. `nd` is described as being the length of randomly generated strings. Given `number_decimals`, an `epsilon` is assigned acting as the upper bound error (traditional in this context) except we set it and use it to enforce exclusion as rounding may invalidate our boundaries given our current approach. Specifically, `random.uniform` is inclusive on both bounds, and if we want to exclusively generate something we are changing the specified bounds with our epsilon because we'll round it later.
While this change fixes the bug, it may be worth considering changes that more …
> Adjusted rounding system for exec simulate simulated floating point params

- tools/python/boutiques/localExec.py
- tools/python/boutiques/schema/examples/example1/example1_docker.json
- tools/python/boutiques/schema/examples/example1/example1_docker_exported.json
- tools/python/boutiques/schema/examples/example1/example1_docker_exported_doi.json
- tools/python/boutiques/schema/examples/example1/example1_docker_exported_doi_python2.json
- tools/python/boutiques/schema/examples/example1/example1_docker_exported_python2.json
- tools/python/boutiques/schema/examples/example1/example1_docker_nonutf8.json
- tools/python/boutiques/schema/examples/example1/example1_docker_with_doi.json
- tools/python/boutiques/schema/examples/example1/exampleTool1.py
- tools/python/boutiques/schema/examples/example1/exampleTool1_nonutf8.py
- tools/python/boutiques/schema/examples/example1/invocation.json
- tools/python/boutiques/tests/boutiques_mocks.py
- tools/python/boutiques/tests/test_data_collection.py
- tools/python/boutiques/tests/test_evaluate.py
- tools/python/boutiques/tests/test_example1.py
- tools/python/boutiques/tests/test_pull.py
- tools/python/boutiques/tests/test_simulate.py
- tools/python/boutiques/tests/test_test.py
Fix for #458.
To test this, added a new input to `example1_docker.json` that takes a list of files. Published a new version of this file on Zenodo: https://zenodo.org/record/2634310.
> Support lists of input files

- tools/python/boutiques/searcher.py
#450 
Set the search to always return a maximum of 9999 results. Right now there are 33 descriptors and I can't imagine we'll ever have so many that this API call will become too slow (maybe one day :stuck_out_tongue:). It then sorts all the results by number of downloads and truncates the results list according to `max_results`.
> Changed bosh search to get and sort all results

- tools/python/boutiques/localExec.py
Fix for #449 
The problem was with list inputs; they were always being cast as strings.
> Fix bosh example

- tools/python/boutiques/publisher.py
- tools/python/boutiques/tests/boutiques_mocks.py
- tools/python/boutiques/tests/test_publisher.py
#402 
Attempting to update a tool published by a different user results in a 403 (forbidden) error from Zenodo when sending the new deposition. When `bosh publish` sees this 403, it returns an error message telling the user that they do not have permission to access the resource and that they cannot update tools that belong to someone else.
Also removed some test code that didn't make sense anymore now that we use mocks, such as checking that a valid Zenodo token works.
> Added specific error message when trying to update a tool authored by a different user

- tools/python/boutiques/localExec.py
- tools/python/boutiques/schema/examples/example1/example1_docker.json
- tools/python/boutiques/tests/test_example1.py
- tools/python/boutiques/tests/test_publisher.py
Small improvements to test coverage:
* Removed dead code testing for container image types in `localExec.py` as unknown image types lead to incorrect descriptors anyway.
* Added a test to `example1_docker.json`
* Added options to existing tests
* Added tests for various publication errors
> Improved test coverage

- .travis.yml
The version of docker2singularity used in Travis has to be fixed and consistent with the version of Singularity used. Otherwise, the boutiques/example:test image converted from Docker might not work.
> Fixed version of docker2singularity

- .travis.yml
- tools/python/boutiques/localExec.py
#477 
This:
- Updates the version of Singularity used on Travis from 2.4 to 2.6, the version currently used on Compute Canada.
- Removes the complex mount path logic meant to work around sylabs/singularity#1469 that has been fixed in Singularity 2.5.
> Singularity mounts

- tools/python/boutiques/prettyprint.py
- tools/python/boutiques/tests/test_pprint.py
Required input arguments (if present) are separated from optional ones. Required arguments were grouped with optional arguments but have the parameter "Optional" at False.
```
=========================================
positional arguments:
[...]
optional arguments:
[...]
required arguments:
[...]
=========================================
```
Config files are listed separate from the output files & output files are listed last. Config files were printed 3rd and had config files listed under output files.
```
=========================================
Config Files:
Name: [...]
=========================================
Output Files:
Name: [...]
```
> Pprint fixes#491

- tools/python/boutiques/localExec.py
- tools/python/boutiques/schema/examples/example3/example3.json
- tools/python/boutiques/tests/test_example3.py
- tools/python/cleanup_tests.sh
- tools/python/config.txt
- tools/python/subdir1/subdir2/config.txt
Addresses #397 
Previous behaviour:
- No truncation of values beyond stripping file extensions
Current behaviour:
- For `output-files` which contain `value-key` substitutions: inputs of `type="File"` used for these substitutions that do not *start* the `path-template` (i.e. `template.find(value-key)` does not return location `0`) will be modified to only insert the `os.path.basename` of the value, rather than the complete path.
> Improved output substitution

- tools/python/boutiques/searcher.py
This fixes the query string in searcher when an empty string was passed to the function.
Since '' is different than None the empty string remained and the request query string was **~ resulting in something like ...?q=**&keyword...`. A 500 Error was returned by Zenodo.
> Zenodo search query support empty string

- tools/python/boutiques/localExec.py
- tools/python/boutiques/tests/test_example.py
- tools/python/boutiques/tests/test_simulate.py
- tools/python/config.txt
Bug caused by optional inputs being added before group restrictions are checked. (#529)
```
~$ bosh example boutiques/schema/examples/tests_good.json -c
An error occurred in validation
Previously saved issues
Input num_input should be disabled by flag_input
[ ERROR ] Problems found with prospective input:
Input num_input should be disabled by flag_input
```
```
~$ bosh example boutiques/schema/examples/tests_good.json -c
{
"config_num": 4,
"file_input": "f_file_input_15.mnc",
"list_int_input": [
46,
-38,
45
],
"num_input": 0.264,
"str_input": "str_str_input_Zf",
"str_input_list": [
"str_str_input_list_MM",
"str_str_input_list_mX",
"str_str_input_list_5a"
]
}
```
> Bexample return error #529

- tools/python/boutiques/searcher.py
It appears if the tool…has never been downloaded, this doesn't exist rather than returning 0.
Fixes issue #535
> Added a catch on version_downloads key

- tools/python/boutiques/schema/examples/example1/Dockerfile
Tests involving `example1.json` are failing because Docker image `centos:latest` is now CentOS8, and the CentOS8 Docker image doesn't come with a Python interpreter. This freezes the Docker image used in `example1.json` to CentOS7.
> Freeze base image used in example1 to CentOS7

- tools/python/boutiques/bosh.py
- tools/python/boutiques/prettyprint.py
- tools/python/boutiques/schema/examples/good_dupFlags.json
- tools/python/boutiques/tests/test_pprint.py
name: "descriptor2func can't handle duplicate command-line flags"
about: pprint error when there are duplicate flags in a valid descriptor
title: 'Bug fix for issue #548 #516 '
#548 #516
Fixed failing execution for pprint (in descriptor2func.py) descriptor contains duplicate flags even if descriptor can be executed by bosh.
```
File "boutiques/tools/python/boutiques/prettyprint.py", line 325, in descInputs
self.parser.add_argument(*inp_args, **inp_kwargs)
[...]
argparse.ArgumentError: argument -duplicate: conflicting option string: -duplicate
```
```
positional arguments:
[PARAM1]              ID: input
Value Key: [PARAM1]
Type: File
List: False
Optional: True
Description: A file
optional arguments:
-duplicate [FLAG1]    ID: flag1
Value Key: [FLAG1]
Type: Flag
List: False
Optional: True …
```
> pprint fix for duplicate flags

- tools/python/boutiques/tests/boutiques_mocks.py
- tools/python/boutiques/tests/test_pull.py
---
name: makeblastdb
about: Changed the mock.patch to mock urlretrieve, which was actually used 
title: 'Bug fix for issue #522 '
---
- The wrong thing was being mocked, and it wasn't being patched properly anyway.
- There seemed to be a change in the current example-tool version that was causing some test failure, so I changed it to use the newest id.
- Since this is a fix in the tests,  not the core codebase, I can confirm the fixed tests
- I am dubious about the changes to the example descriptor...
- This fixes a test so that makeblastdb will stop getting inflated numbers on zenodo
The makeblastdb entry on zenodo is downloaded every time while testing.
A mock descriptor for makeblastdb is now used.
- [ x] No
I switched to patching boutiques.puller.urlretrieve. I …
> Fixed #522

- tools/python/setup.py
---
name: Fix travis for Python 3.4 jobs
title: Bug fix for issue #571 
---
Specify PyYAML for python version 3.4 because PyYAML dropped support for Py3.4
> Travis pyyaml py3.4

- tools/python/boutiques/bosh.py
- tools/python/boutiques/importer.py
- tools/python/boutiques/tests/test_import.py
---
name: Missing doc for `bosh import dcpt`
about: Clarification of help text
title: Bug fix for issue #579
labels: bug
---
Clarify `bosh` & `bosh import`'s help text.
Renamed `dcpt` to `docopt` in `bosh import` and modified help text + refactored accordingly.
Added list of available options in the help text of `bosh -h`
```
usage: Imports old descriptor or BIDS app or CWL descriptor to spec.
[-h] [-o OUTPUT_INVOCATION] [-i INPUT_INVOCATION]
{bids,0.4,cwl,dcpt} output_descriptor input_descriptor
positional arguments:
{bids,0.4,cwl,dcpt}   Type of import we are performing
```
```
usage: Imports old descriptor or BIDS app or CWL descriptor or docopt script to spec.
[-h] [-o OUTPUT_INVOCATION] [-i INPUT_INVOCATION]
type output_descriptor input_descriptor
positional arguments:
type …
```
> Missing doc for `bosh import dcpt`

- tools/python/boutiques/bosh.py
- tools/python/boutiques/creator.py
- tools/python/boutiques/importer.py
- tools/python/boutiques/publisher.py
- tools/python/boutiques/templates/ordered_keys_desc.json
- tools/python/boutiques/tests/test_import.py
- tools/python/boutiques/util/utils.py
- tools/python/boutiques/validator.py
#480 #520 
Keep the preferred ordering of arguments to adhere to the principle of the least user astonishment. While ordering might be useful it is not what most users would expect, and obscure the fact that there is actual semantic change (added property).
Most descriptor/invocation outputs are alphabetically sorted.
Keep the preferred ordering of arguments according to a template or the original descriptor. 
Keep ordering of invocations according to the inputs of a descriptor.
Custom sort for descriptor: defaults to ordering given by _tools/python/boutiques/templates/ordered_keys_desc.json_
Custom sort for invocation: no default, all set to order by input descriptor.
> Improve desc invoc outputs

- tools/python/boutiques/bosh.py
- tools/python/boutiques/exporter.py
- tools/python/boutiques/localExec.py
- tools/python/boutiques/puller.py
- tools/python/boutiques/tests/test_example.py
- tools/python/boutiques/tests/test_pull.py
- tools/python/boutiques/util/utils.py
- tools/python/boutiques/validator.py
#444 
Cache Zenodo descriptors into different directories depending on their source (prod or sandbox).
Cache directory for zenodo descriptors are the same regardless from where the descriptor is pulled from Zenodo (prod/sandbox). Might cause boutiques to fetch the wrong descriptor if there's are descriptors with duplicated ZIDs (ZIDs are not guaranteed to be distinct across prod and sandbox).
Zenodo descriptors are pulled into separate directories depending on their origin:
`~/.cache/boutiques/production`
`~/.cache/boutiques/sandbox`
Descriptors that are currently cached in the old directory `~/.cache/boutiques/` will be ignored.
All bosh functions that take in a descriptor (json string or zenodo id) will have a `--sandbox` flag added so in the event a zenodo ID is passed, the user can …
> Zenodo cache dir

- tools/python/boutiques/localExec.py
Enables finding files that match patterns rather than just have explicit filenames specified in the descriptor/invocation. To do this, I replaced an `op.exists` with a `glob`.
> replaced op.exists with a glob so regexes can be matched

- tools/python/boutiques/bosh.py
- tools/python/boutiques/deprecate.py
- tools/python/boutiques/publisher.py
- tools/python/boutiques/puller.py
- tools/python/boutiques/schema/descriptor.schema.json
- tools/python/boutiques/searcher.py
- tools/python/boutiques/tests/boutiques_mocks.py
- tools/python/boutiques/tests/test_deprecate.py
- tools/python/boutiques/tests/test_search.py
- tools/python/boutiques/zenodoHelper.py
#428 #402 
Allow original publisher of tool on Zenodo to deprecate it so newer versions (as separate record) can be published by a different user.
No way to remove outdated zenodo tools from `bosh search` results. 
No official way to link old version of tool to a newer tool (as separate record).
`bosh deprecate [ZID1] --zenodo-token [ZTOKEN]` 
Optional: `--by [ZID2]`
Will add deprecate keyword to the newest version of the tool ZID1 and it will no longer appear in `bosh search` (can be made visible with `--verbose` search).
If argument `--by [ZID2]` is added, tool ZID1 will have an additional `deprecated-by-doi:[ZID2]` keyword. As well as a "New versions" related identifier pointing to tool ZID2.
Tool descriptor will contain field `'deprecated-by-doi': [True OR ZID2]` depending on whether …
> Bosh deprecate

- tools/python/boutiques/localExec.py
- tools/python/boutiques/schema/examples/list_separator.json
- tools/python/boutiques/schema/examples/list_separator_inv.json
#577 
List separators should only be added between items, not before the first item or after the last.
When simulating inputs for an input of type list and list contains repeating value, an extra list separator is added to the end of the list.
List separator is added only between items, even if list contains repeating items.
Bug caused by the following condition falsely passing if the list 'val' contains repeating items
```python3
if val.index(x) == len(val)-1:
s_val += s
```
> Extra line separator #577

- tools/python/boutiques/localExec.py
- tools/python/boutiques/schema/examples/bad_conIndexImage.json
- tools/python/boutiques/schema/examples/example1/conImage_with_index.json
- tools/python/boutiques/schema/examples/example1/input_invoc.json
- tools/python/boutiques/tests/test_example1.py
- tools/python/boutiques/tests/test_validator.py
- tools/python/boutiques/validator.py
- tools/python/cleanup_tests.sh
#588 
Various commands crash when the container image contains an index name
Commands crash because index is appended to the command name even though it's already present in the image name.
Index in image name is matched with regex and `container-image`'s `index` value will not be prepended to image name.
Validator raises error if an index is found in `container-image`'s `image` and it doesn't match the `index` value.
> Support image name with index

- RELEASE.md
- tools/python/boutiques/bosh.py
#599 
General description of bosh functions missing from Sphinx docs.
Modified `RELEASE.md` to add missing steps for sphinx-argparse installation.
Descriptions are now generated correctly.
sphinx-argparse doesn't generate description text unless `description` keyword argument is explicitly used in `ArgumentParser` constructor.
> Docs missing command descriptions

- tools/python/boutiques/searcher.py
- tools/python/boutiques/tests/boutiques_mocks.py
- tools/python/boutiques/tests/test_search.py
Related issues
#604
`bosh search` should return the upload date next to the other fields returned when using the verbose option.
The following columns are shown in `bosh search [INPUT] --verbose`
`ID, TITLE, DESCRIPTION, DEPRECATED, DOWNLOADS, AUTHOR, VERSION, DOI, SCHEMA, VERSION, CONTAINER, TAGS`
`ID, TITLE, DESCRIPTION, PUBLICATION DATE, DEPRECATED, DOWNLOADS, AUTHOR, VERSION, DOI, SCHEMA, VERSION, CONTAINER, TAGS`
Date located in `hit["metadata"]['publication_date']`, there's also `hit['created']` which contains datetime if needed.
> Added publication date to bosh search --verbose

- tools/python/boutiques/bosh.py
- tools/python/boutiques/creator.py
- tools/python/boutiques/templates/basic.json
- tools/python/boutiques/tests/test_creator.py
- tools/python/boutiques/util/utils.py
#503 
`boutiques.creator.CreateDescriptor` should have an option to convert all parameter names to CamelCase. When this option is used, all input IDs should be written in Camel Case.
NA
Added `--camel-case` option to `creator.CreateDescriptor` (regrettably not --camelCase for the sake of consistency).
1) Gets input ids from descriptor object
2) Util functions convert ids to camel case
3) All instances of input ids (within single/double quotes) are replaced in plain-text descriptor
4) Descriptor is reloaded
> Added camel case option for descriptor inputs

- tools/python/boutiques/bosh.py
- tools/python/boutiques/localExec.py
- tools/python/boutiques/schema/examples/test_simulate_consistency.json
- tools/python/boutiques/schema/examples/test_simulate_consistency_configFile.json
- tools/python/boutiques/tests/test_example.py
- tools/python/boutiques/tests/test_simulate.py
#578 
`bosh exec simulate` should yield consistent results regardless of an invocation's presence through option `-i`.
Descriptor's `optional: true` inputs with `default-value` are not added to simulated command-line output, but are added when an invocation (created by bosh example) is supplied.
`optional: true` inputs with `default-value` are added to simulated command-line output consistently.
In `simulate`, `localExec.addDefaultValues` is called before `LocalExecutor.generateRandomParams`.
`LocalExecutor.generateRandomParams` no longer takes argument `n` for the number of iterations to attempt. This is to prevent the `LocalExecutor.in_dict` from clearing before each iteration (`in_dict` contains inputs to use when generating random param values).
> Bosh simulate consistency patch

- tools/python/boutiques/bosh.py
- tools/python/boutiques/conftest.py
- tools/python/boutiques/test.py
#463 #5 
Enable imagepath for `bosh test` to speed up testing within a tool.
`bosh test` uses `bosh exec launch` but does not have the `--imagepath` option enabled.
`--imagepath` option is added to `bosh test` so the image path is passed to `bosh exec launch` during individual tests.
During `bosh test`, additional options such as `--skip-data-collection` and `--imagepath` are added to a dict and passed to `test` in test.py. These additional options are appended to launch arguments.
> Btest use imagepath

- tools/python/boutiques/dataHandler.py
#610 
`FileExistsError` when running Boutiques in a multiprocessing environment (Travis).
Added `exists_ok=True` to os.makedirs (default: `exists_ok=False`, docs: ```If the target directory already exists, raise an OSError if exist_ok is False. Otherwise no exception is raised. This is recursive.```)
> FileExistsError during concurrent boutiques instances

- tools/python/boutiques/schema/examples/test_forward_slash_toolName.json
- tools/python/boutiques/searcher.py
- tools/python/boutiques/tests/test_publisher.py
- tools/python/boutiques/tests/test_search.py
#617
Publishing tool with name containing a '/' will cause:
`[ ERROR (400) ] Error searching Zenodo`
OK (returns doi)
Replaced '/' in query with '.' wildcard.
> Publisher crash forwardslash

- tools/python/boutiques/localExec.py
#630 
To not append `-l` when calling a custom shell.
Boutiques always append " -l" (space dash ell) to the shell's path in that script, which won't work when the shell invoked doesn't have a -l option.
`-l` is only appended to script when calling the default `/bin/sh`
> -l flag only applied if shell path is /bin/sh

- tools/python/boutiques/localExec.py
#629 
Removed superfluous message for container engine versioning
Caused by docker installation check before choosing type of container to run.
```
/bin/sh: docker: command not found
singularity version 3.6.1
all done
```
stderr for docker is removed during singularity container exec
```
singularity version 3.6.1
all done
```
Check docker/singularity installation AFTER choosing container type
> Docker used during sing exec

- boutiques/zenodoHelper.py
#658 
Adjust search query to new Zenodo behavior that doesn't match keywords with hyphens (most likely due to a backend update).
bosh search returns nothing, because all boutiques tools have "schema-version:0.5" as keyword and keywords with hyphens don't match the query regexp.
bosh search now returns correct output.
query is now done separately on keywords "schema" and "version". Best guess is that the backend splits "schema-version" in two keywords.
> Fixed search following change of behavior in Zenodo API (#658)

- .travis.yml
- README.md
- boutiques/bosh.py
- boutiques/dataHandler.py
- boutiques/importer.py
- boutiques/nexusHelper.py
- boutiques/publisher.py
- boutiques/searcher.py
- boutiques/tests/test_simulate.py
- boutiques/tests/validator/bad.json
- boutiques/util/utils.py
- boutiques/validator.py
- boutiques/zenodoHelper.py
- setup.py
Makes Boutiques lighter
Installation with `pip install boutiques` would install every dependency, even if I didn't plan on using many functions w/in the lib.
Now, the base install comes with the minimal set of dependencies to use/validate descriptors, and all the rest can be installed with `pip install boutiques[all]`.
- added `importCatcher()` decorator to wrap functions which require non-essential dependencies
- moved non-essential dependency imports to within functions using them
- the above closes #645 
- updated docs
- also addressed #644 by adding a validation condition
> created minimal install bundle

- tools/python/boutiques/searcher.py
- tools/python/boutiques/tests/boutiques_mocks.py
- tools/python/boutiques/tests/test_search.py
Fixes #655 
This allows Zenodo records without a version specified to be processed.
Bosh search throws a KeyError before returning anything.
Boutiques will return a record with "VERSION" set to "unknown".
> Allow missing tool version, assigning "unknown"

- tools/python/boutiques/localExec.py
- tools/python/boutiques/prettyprint.py
addresses warnings I got
/home/yoh/proj/misc/boutiques/tools/python/boutiques/localExec.py:1066: SyntaxWarning: "is not" with a literal. Did you mean "!="?
if val is not None and val is not "":
/home/yoh/proj/misc/boutiques/tools/python/boutiques/prettyprint.py:125: SyntaxWarning: "is not" with a literal. Did you mean "!="?
if config_info is not "Config Files:" else ""
/home/yoh/proj/misc/boutiques/tools/python/boutiques/prettyprint.py:318: SyntaxWarning: "is not" with a literal. Did you mean "!="?
if req_inp_descr is not "":
/home/yoh/proj/misc/boutiques/tools/python/boutiques/prettyprint.py:323: SyntaxWarning: "is not" with a literal. Did you mean "!="?
if opt_inp_descr is not "":
> Use != instead of is not with literal

- boutiques/bosh.py
- boutiques/boshParsers.py
- boutiques/dataHandler.py
---
name: inspect latest provenance file
about: display last created provenance file
title: 'command-line option for the last created provenance'
assignees: ''
---
For ease of access to the latest created provenance file, and option `-l, --latest` added to the `bosh data inspect`. The cache directory is sorted by modified timestamp, and the first file is displayed
> Command-line option for 'bosh data inspect' to display latest provenance file

- boutiques/zenodoHelper.py
Bosh publish was broken due to change in Zenodo authentication headers.
Fixes Zenodo authentication headers
Bosh publish doesn't work because Zenodo authentication fails
Bosh publish works
- [x ] No
Fixed authentication headers in every HTTP request to Zenodo, following advice from Zenodo support
> Fixed Zenodo authentication header

- .github/workflows/tests.yml
- pyproject.toml
- drop python 3.8 and support python 3.13
- closes none
> [MAINT] Drop python 3.8 and support python 3.13

- boutiques/boshParsers.py
- boutiques/localExec.py
---
name: [FIX] error message when no `output-files` exist in descriptor.
title: 'Feature implementation | Bug fix for issue #669'
assignees: ''
---
fix #669
See #669 for details.
When no `output-files` exist in descriptor, `bosh exec  launch` display error message yet succeed.
No longer display the error message.
Verify that the `output-files` key exist before querying it.
> [FIX] error message when no `output-files` exist in descriptor.

- GETTING_STARTED.md
- boutiques/bosh.py
- boutiques/boshParsers.py
- boutiques/localExec.py
- boutiques/tests/test_example1.py
#650, #688
Add support for apptainer runtime as discussed in [#688](https://github.com/boutiques/boutiques/pull/688#issuecomment-2612600351) and [#650](https://github.com/boutiques/boutiques/issues/650#issuecomment-2612633629).
All changes in this PR should be backwards-compatible, the intent is to support hypothetical environments where the `apptainer` command exists but `singularity` doesn't, and to allow explicit selection of the `apptainer` runtime with `bosh exec launch --force-apptainer`.
Detail of changes:
- possible values for the `container-image.type` descriptor field remain unchanged: only `docker` or `singularity`
- when the `singularity` command is not found, but the `apptainer` command exists, then call apptainer instead of failing. This is handled in …
> Feature implementation for issue #650 - apptainer support
