- README.md
- descriptor.schema.json
@rafaelfsilva please have a look and merge if you agree.
> Updates in README and schema.

- descriptor.schema.json
> Adding support for groups in Boutiques schema

- README.md
- descriptor.schema.json
> Updates in README and documentation

- README.md
- descriptor.schema.json
Adds new features to the schema (as in #19) that have been implemented in aces/cbrain#426
> Updating schema with new features

- tools/invocationSchemaHandler.py
Adds `invocationSchemaHandler.py`, which is capable of:
- Generating a json invocation schema from a Boutiques tool descriptor
- Checking json format inputs with respect to an invocation schema (potentially generated from the tool descriptor on the fly)
See also #52, for manually written example invocation schemas.
> Adding an invocation schema generator

- schema/descriptor.schema.json
- tools/localExec.py
For #56. Updates the schema and the local executor tool.
> Adding environment variable support

- schema/descriptor.schema.json
- tools/validator.rb
Attempts to satisfy the requirements of #51 and #58. 
If the schema changes seem ok, let me know and I will update the tools (and cbrain) as well.
> Add path constraints to Files, and support for more containers.

- schema/README.md
@tta9: please check that all your latest additions are now documented.
> Documents the latest schema additions.

- Dockerfile
- tools/README.md
- tools/localExec.py
Updates localExec.py to the latest schema version.
Includes support for `uses-absolute-paths` and specifying a `working-directory` for containers in the boutiques descriptor. Also added the option to run containers as the current user (so that output files are not owned by root).
> Path handling

- schema/README.md
- schema/descriptor.schema.json
- tools/localExec.py
Adds the uses-absolute-path property to the schema, readme, and localexec.
Also, fixes some bugs in the localexec.
> uses-absolute-path for output files

- examples/Dockerfile
- examples/output-file/output.json
- examples/output-file/output.sh
- tools/localExec.py
Also, input file extensions are now correctly stripped.
> Fixes #82 and adds an example for output files

- examples/README.md
- examples/custom-properties/custom.json
- examples/invalid/typos/README.md
- examples/invalid/typos/invalid-container.json
- examples/invalid/typos/invalid-input.json
- examples/invalid/typos/invalid-output-file.json
- examples/invalid/typos/invalid-tool.json
- schema/README.md
- schema/descriptor.schema.json
Schema updates to address #69, #72 and #79, with corresponding examples and documentation.
> Schema updates

- examples/Dockerfile
- examples/enum/enum.json
- examples/enum/enum.sh
- examples/invalid/enum/enum-bad-default.json
- examples/invalid/enum/enum-no-choice.json
- examples/list/list.json
- examples/list/list.sh
- examples/output-flag-separator/output-flag.json
- examples/output-flag-separator/output-flag.sh
- schema/descriptor.schema.json
- tools/invocationSchemaHandler.py
- tools/localExec.py
- tools/validator.rb
@johnflavin, you may want to have a look too (for #59).
> Fixes for #59 and #79

- tools/python/boutiques/localExec.py
- tools/python/boutiques/schema/descriptor.schema.json
- tools/python/boutiques/schema/examples/good.json
- Added entrypoint flag to schema
- Moved `singularity` to be handled like `docker` rather than `rootfs`
- Generalized `localExec.py` for singularity and docker containers
> Schema & localExec (i.e. bosh) updates

- tools/README.md
- tools/python/boutiques/__init__.py
- tools/python/boutiques/invocationSchemaHandler.py
- tools/python/boutiques/schema/examples/good.json
- tools/python/boutiques/schema/examples/good_invocation.json
- tools/python/boutiques/tests/test_invocation.py
1. Changed the interface. `bosh-invocation` now takes a descriptor and adds an invocation schema to it. If an invocation is passed (optional), it will validate it against the invocation schema. 
2. Wrote a basic test.
> Simplified bosh-invocation

- examples/Getting Started with Boutiques.ipynb
> Fixed typo in notebook tutorial

- tools/python/boutiques/bosh.py
- tools/python/boutiques/evaluate.py
- enabled queries that don't end in `/`
- forced missing fields to evaluate to `false` in the evaluation
(sorry I didn't get these in in time for the last PR!)
> bug fixes for evaluate

- tools/python/setup.py
Last commit before release 0.5.5.
> Bumped package version

- README.md
- tools/python/setup.py
Release notes:
- New command: `bosh test`.
- Fixes in Singularity support.
Added documentation for `bosh test` in README.md
> Bumped version number

- .travis.yml
- tools/python/boutiques/__init__.py
- tools/python/boutiques/bids.py
- tools/python/boutiques/bosh.py
- tools/python/boutiques/conftest.py
- tools/python/boutiques/evaluate.py
- tools/python/boutiques/exporter.py
- tools/python/boutiques/importer.py
- tools/python/boutiques/invocationSchemaHandler.py
- tools/python/boutiques/localExec.py
- tools/python/boutiques/publisher.py
- tools/python/boutiques/test.py
- tools/python/boutiques/tests/test_bosh.py
- tools/python/boutiques/tests/test_evaluate.py
- tools/python/boutiques/tests/test_example1.py
- tools/python/boutiques/tests/test_example2.py
- tools/python/boutiques/tests/test_exec.py
- tools/python/boutiques/tests/test_import.py
- tools/python/boutiques/tests/test_invocation.py
- tools/python/boutiques/tests/test_publisher.py
- tools/python/boutiques/tests/test_pythoninterface.py
- tools/python/boutiques/tests/test_test.py
- tools/python/boutiques/validator.py
- Added `pycodestyle` to `.travis.yml` to test PEP8 compliance.
- Reformatted most of the source files to comply to PEP8.
Fixes #203.
> Compliance to PEP8

- tools/python/boutiques/bosh.py
- tools/python/boutiques/localExec.py
> Minor fixes

- .travis.yml
- tools/python/boutiques/bids.py
- tools/python/boutiques/bosh.py
- tools/python/boutiques/invocationSchemaHandler.py
- tools/python/boutiques/localExec.py
- tools/python/boutiques/schema/descriptor.schema.json
- tools/python/boutiques/tests/test_bids.py
- tools/python/boutiques/tests/test_validator.py
- tools/python/boutiques/validator.py
* Added JSONLint of JSON schema.
* `bosh` now returns validation exception when called from a Python script, but only prints an error message when called from the command-line (fix for #193). 
* Minor style fixes
> JSONLint and minor style fixes

- tools/python/boutiques/schema/descriptor.schema.json
- tools/python/boutiques/schema/examples/test_exclusive_minimum.json
- tools/python/boutiques/tests/test_validator.py
- tools/python/boutiques/validator.py
* Fixed #247 by removing dependency of `exclusive-minimum` and `exclusive-maximum` to type `Number`.
* Added a test that asserts that descriptors with `exclusive-minimum` but no `minimum` aren't valid.
* Fixed exception handling bug in validator.
> Fixed #247 and exception handling in validator

- README.md
- RELEASE.md
- tools/python/README.rst
- tools/python/setup.py
- Added RST version of the markdown README to the package directory, to be added and parsed by pypi (does not support markdown :()
- Pypi docs now are detailed: https://pypi.org/project/boutiques/
> Updated Pypi documentation

- tools/python/boutiques/bosh.py
- tools/python/boutiques/tests/test_example1.py
As reported by @camarasu (thanks!).
> Fixed regression on #117

- tools/python/boutiques/schema/examples/bids-apps/example_good/test-import-ref.json
- tools/python/boutiques/schema/examples/bids_bad1.json
- tools/python/boutiques/schema/examples/bids_bad2.json
- tools/python/boutiques/schema/examples/bids_good.json
- tools/python/boutiques/templates/bids-app.json
addresses "name of a BIDS App #292" issue
> Mention BIDS in the name of imported bids application 

- tools/python/boutiques/bids.py
- tools/python/boutiques/creator.py
- tools/python/boutiques/schema/examples/bids-apps/example_good/test-import-ref.json
- tools/python/boutiques/schema/examples/bids_bad1.json
- tools/python/boutiques/schema/examples/bids_bad2.json
- tools/python/boutiques/schema/examples/bids_good.json
- tools/python/boutiques/templates/bids-app.json
- tools/python/boutiques/tests/test_creator.py
- tools/python/boutiques/validator.py
- fixed validator bug that failed to pass default values of lists even in list type inputs
- made bids apps consistent with creator apps (using square brackets to prevent parameter nesting issues)
- fixed creator for another type of list arguments
> Minor bug fixes

- README.md
- tools/python/boutiques/creator.py
- tools/python/boutiques/invocationSchemaHandler.py
- tools/python/boutiques/tests/test_creator.py
- tools/python/cleanup_tests.sh
Added a simple method to the creator that creates invocations from parser args, and associated docs and test
> Create invocations from argparse parsers

- tools/python/boutiques/publisher.py
- tools/python/boutiques/schema/examples/good.json
- tools/python/boutiques/tests/boutiques_mocks.py
- tools/python/boutiques/tests/test_evaluate.py
- tools/python/boutiques/tests/test_example1.py
- tools/python/boutiques/tests/test_publisher.py
- tools/python/boutiques/tests/test_pull.py
- tools/python/boutiques/tests/test_search.py
- tools/python/boutiques/tests/test_simulate.py
- tools/python/boutiques/tests/test_test.py
- tools/python/setup.py
Issue #289
Created mocks for all the Zenodo server calls so that the tests don't randomly fail due to Zenodo's server being weird.
Note: #368 should be merged first so that I can use the mocks for the new tests.
> Mock zenodo server

- CONTRIBUTING.md
- GETTING_STARTED.md
#384
This is just based off my memory of when I first set up my environment so it's possible I am missing things. Different systems might have different setup requirements, but I tried to make this guide as general as possible.
> Readme for setting up local dev environment

- .travis.yml
- tools/python/boutiques/importer.py
- tools/python/boutiques/localExec.py
- tools/python/boutiques/publisher.py
- tools/python/boutiques/tests/test_example1.py
- tools/python/boutiques/tests/test_export.py
- tools/python/boutiques/tests/test_import.py
- tools/python/boutiques/tests/test_logger.py
- tools/python/boutiques/validator.py
Fixed the overindentation that the new version of pycodestyle was complaining about.
> Fixed codestyle

- tools/python/boutiques/bosh.py
> Fixed bosh invocation for "-v mount"

- tools/python/boutiques/publisher.py
- tools/python/boutiques/schema/descriptor.schema.json
- tools/python/boutiques/schema/examples/example1/example1_docker.json
#359 
Descriptors can now have an array of URLs where the tool is installed. On publication, URLs are published through relation 'hasPart'.
> Online platforms

- tools/python/boutiques/bosh.py
- tools/python/boutiques/localExec.py
- tools/python/boutiques/tests/test_prepare.py
> Fixed bug where specifying only the basename for imagepath failed

- .travis.yml
> Travis CI is ignoring the jsonschema requirement, this forces it

- tools/python/boutiques/localExec.py
- tools/python/boutiques/schema/examples/list_separator.json
- tools/python/boutiques/schema/examples/list_separator_inv.json
- tools/python/boutiques/tests/test_list_separator.py
Fix for a small bug I noticed today.
> Fix list separator for file inputs

- .travis.yml
- tools/python/boutiques/localExec.py
- tools/python/boutiques/schema/examples/example1/example1_docker.json
- tools/python/boutiques/tests/test_evaluate.py
- tools/python/boutiques/tests/test_example1.py
#483 
Config files can now be located in non-existent sub-directories that will be created at runtime. Tests were updated accordingly.
> Config files in sub-directories

- tools/python/boutiques/importer.py
> Fix for entrypoint handling

- tools/python/boutiques/dataHandler.py
---
name: processes records into list of unique names and descriptors
title: 'Bug fix for issues #559 and #562'
labels: bug fix
assignees: '@glatard'
---
Failure to publish many records (#559) appears to be due to redundant part-linking (#562)
Enable publication of large records :)
> processes records into list of unique names and descriptors

- schema/README.md
> Updated schema doc

- .travis.yml
---
name: Test with Singularity v3.4
about: Modified Travis config
title: 'Feature implementation #560 
---
Update Travis builds' singularity version to 3.4.2
In Travis:
Go1.7 -> Go1.12
Singularity2.6.1 -> Singularity3.4.2
Singularity release link updated
> Test with Singularity v3.4

- tools/python/boutiques/bosh.py
- tools/python/boutiques/localExec.py
- tools/python/boutiques/publisher.py
- tools/python/boutiques/schema/examples/baremetal/test_baremetal.json
- tools/python/boutiques/schema/examples/baremetal/test_baremetal_invoc.json
- tools/python/boutiques/schema/examples/no_container.json
- tools/python/boutiques/tests/test_no_container.py
- tools/python/boutiques/tests/test_publisher.py
---
name: Bare metal execution
title: Feature implementation #511 
---
Run command line of a tool outside of a container with ```--no-container```
Example: ```bosh exec launch [descriptor] [invocation] --no-container``` 
```--no-container``` flag defaults to false.
In _localExec.LocalExecutor.execute_, setting ```conImage``` to None and ```conIsPresent``` to False will run command locally.
> Baremetal exec

- tools/python/boutiques/localExec.py
- tools/python/boutiques/util/utils.py
Addresses the Zenodo portion of  #591
> Fixed broken descriptor loading by doi

- tools/python/boutiques/localExec.py
> added doi pop prior to zenodo/loaded descriptor comparison

- RELEASE.md
- tools/sphinx/argparse_docs.py
* Typo in RELEASE.md
* Removed parsing of README.rst in doc generation script
> Minor fixes in doc generation process

- tools/python/boutiques/dataHandler.py
- tools/python/boutiques/publisher.py
- tools/python/boutiques/puller.py
- tools/python/boutiques/searcher.py
- tools/python/boutiques/zenodoHelper.py
NA
Refactoring
Relocated Zenodo related functions to zenodoHelper class.
Minor refactoring in dataHandler, publisher, puller, and searcher.
> Zenodo helpers relocation (1)

- .codespellrc
- .github/workflows/codespell.yml
- GETTING_STARTED.md
- tools/python/boutiques/conftest.py
- tools/python/boutiques/creator.py
- tools/python/boutiques/importer.py
- tools/python/boutiques/searcher.py
- tools/python/boutiques/test.py
- tools/python/boutiques/util/utils.py
---
name: codespell
about: Fix some typos found in the code using codespell
title: 'codespell'
assignees: ''
---
I found this branch ready to go but never submitted as a PR, so catching up during OHBM
> codespell: add config and action to codespell the code to avoid known typos

- .github/workflows/tests.yml
- .gitignore
- boutiques/tests/boutiques_mocks.py
- boutiques/tests/test_data_handler.py
- boutiques/tests/test_deprecate.py
- boutiques/tests/test_publisher.py
- boutiques/zenodoHelper.py
---
name: Feature or bug fix name
title: 'Feature implementation | Bug fix'
assignees: ''
---
Fix part of the failing tests
> [BUG] fix some of the failing tests ++ Run test on `fix-ci` branch

- .github/workflows/tests.yml
- boutiques/tests/boutiques_mocks.py
- boutiques/tests/test_example1.py
- boutiques/tests/test_validator.py
- pyproject.toml
Uploaded a new record and updated record id in the mock.
---
name: Feature or bug fix name
title: 'Feature implementation | Bug fix for issue #<000>'
assignees: ''
---
> Fix tests for release

- boutiques/tests/test_data_handler.py
The sandbox has been down for over a week now. We expect the testto fail for now
to prevent the test suite to fail.
---
name: Feature or bug fix name
title: 'Feature implementation | Bug fix for issue #<000>'
assignees: ''
---
> XFAIL Nexus token validation, sandbox server is down.

- boutiques/tests/boutiques_mocks.py
- boutiques/tests/test_deprecate.py
- boutiques/zenodoHelper.py
Fix the expected response when zenodo is not accessible.
> [BUG] fix upload command
